{"uid":"9ad585bb286f2d66","name":"test_parameterized_query_with_special_chars[remote]","fullName":"tests.integration.dbapi.async.V2.test_queries_async#test_parameterized_query_with_special_chars","historyId":"3c227fd5299b594e8a95a47d7ec2769d","time":{"start":1754402412634,"stop":1754402450077,"duration":37443},"description":"Query parameters are handled properly.","descriptionHtml":"<p>Query parameters are handled properly.</p>\n","status":"broken","statusMessage":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","statusTrace":"+ Exception Group Traceback (most recent call last):\n  |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/trio/_core/_run.py\", line 1070, in __aexit__\n  |     raise combined_error_from_nursery\n  | exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pytest_trio/plugin.py\", line 195, in _fixture_manager\n    |     yield nursery_fixture\n    |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pytest_trio/plugin.py\", line 250, in run\n    |     await self._func(**resolved_kwargs)\n    |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/tests/integration/dbapi/async/V2/test_queries_async.py\", line 274, in test_parameterized_query_with_special_chars\n    |     await c.execute(\n    |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/firebolt/async_db/cursor.py\", line 397, in execute\n    |     await self._do_execute(\n    |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/firebolt/async_db/cursor.py\", line 245, in _do_execute\n    |     await self._execute_single_query(\n    |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/firebolt/async_db/cursor.py\", line 299, in _execute_single_query\n    |     await self._handle_query_execution(\n    |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/firebolt/async_db/cursor.py\", line 328, in _handle_query_execution\n    |     await self._raise_if_error(resp)\n    |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/firebolt/async_db/cursor.py\", line 157, in _raise_if_error\n    |     raise_error_from_response(resp)\n    |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/firebolt/utils/util.py\", line 189, in raise_error_from_response\n    |     resp.raise_for_status()\n    |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/httpx/_models.py\", line 763, in raise_for_status\n    |     raise HTTPStatusError(message, request=request, response=self)\n    | httpx.HTTPStatusError: Server error '502 Bad Gateway' for url 'https://automation-firebolt.api.us-east-1.staging.firebolt.io/?database=integration_testing__1754402296837&engine=integration_testing__1754402296837&output_format=JSON_Compact'\n    | For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n    +------------------------------------","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"engine_name","time":{"start":1754402403818,"stop":1754402403819,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"service_secret","time":{"start":1754402403819,"stop":1754402403819,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"auth","time":{"start":1754402403819,"stop":1754402403984,"duration":165},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"service_id","time":{"start":1754402403819,"stop":1754402403819,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"database_name","time":{"start":1754402403819,"stop":1754402403819,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"api_endpoint","time":{"start":1754402403984,"stop":1754402403984,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"account_name","time":{"start":1754402403984,"stop":1754402403984,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"core_auth","time":{"start":1754402405271,"stop":1754402405271,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"core_url","time":{"start":1754402405271,"stop":1754402405271,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"connection","time":{"start":1754402412633,"stop":1754402412633,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"Query parameters are handled properly.","status":"broken","statusMessage":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","statusTrace":"+ Exception Group Traceback (most recent call last):\n  |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/trio/_core/_run.py\", line 1070, in __aexit__\n  |     raise combined_error_from_nursery\n  | exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pytest_trio/plugin.py\", line 195, in _fixture_manager\n    |     yield nursery_fixture\n    |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pytest_trio/plugin.py\", line 250, in run\n    |     await self._func(**resolved_kwargs)\n    |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/tests/integration/dbapi/async/V2/test_queries_async.py\", line 274, in test_parameterized_query_with_special_chars\n    |     await c.execute(\n    |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/firebolt/async_db/cursor.py\", line 397, in execute\n    |     await self._do_execute(\n    |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/firebolt/async_db/cursor.py\", line 245, in _do_execute\n    |     await self._execute_single_query(\n    |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/firebolt/async_db/cursor.py\", line 299, in _execute_single_query\n    |     await self._handle_query_execution(\n    |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/firebolt/async_db/cursor.py\", line 328, in _handle_query_execution\n    |     await self._raise_if_error(resp)\n    |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/firebolt/async_db/cursor.py\", line 157, in _raise_if_error\n    |     raise_error_from_response(resp)\n    |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/firebolt/utils/util.py\", line 189, in raise_error_from_response\n    |     resp.raise_for_status()\n    |   File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/httpx/_models.py\", line 763, in raise_for_status\n    |     raise HTTPStatusError(message, request=request, response=self)\n    | httpx.HTTPStatusError: Server error '502 Bad Gateway' for url 'https://automation-firebolt.api.us-east-1.staging.firebolt.io/?database=integration_testing__1754402296837&engine=integration_testing__1754402296837&output_format=JSON_Compact'\n    | For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502\n    +------------------------------------","steps":[],"attachments":[{"uid":"19e889ef6f71140b","name":"log","source":"19e889ef6f71140b.txt","type":"text/plain","size":135}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests.integration.dbapi.async.V2"},{"name":"suite","value":"test_queries_async"},{"name":"host","value":"pkrvmjbmru5nbw0"},{"name":"thread","value":"2472-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.dbapi.async.V2.test_queries_async"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"connection","value":"'remote'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"9ad585bb286f2d66.json","parameterValues":["'remote'"]}