{"uid":"300cea5cb07123ab","name":"test_concurent_auth_lock","fullName":"tests.unit.V1.client.test_client_async#test_concurent_auth_lock","historyId":"b023188373c629db97202ca7e0b96efc","time":{"start":1732763878520,"stop":1732763878623,"duration":103},"status":"broken","statusMessage":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","statusTrace":"+ Exception Group Traceback (most recent call last):\n  |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_core/_run.py\", line 1039, in __aexit__\n  |     raise combined_error_from_nursery\n  | exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Exception Group Traceback (most recent call last):\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pytest_trio/plugin.py\", line 195, in _fixture_manager\n    |     yield nursery_fixture\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pytest_trio/plugin.py\", line 250, in run\n    |     await self._func(**resolved_kwargs)\n    |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/tests/unit/V1/client/test_client_async.py\", line 167, in test_concurent_auth_lock\n    |     for url in urls:\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_core/_run.py\", line 1039, in __aexit__\n    |     raise combined_error_from_nursery\n    | exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (10 sub-exceptions)\n    +-+---------------- 1 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1663, in _send_handling_auth\n      |     raise exc\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1652, in _send_handling_auth\n      |     next_request = await auth_flow.asend(response)\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 174, in async_auth_flow\n      |     if self._lock.locked() and self._lock._owner_task == get_current_task():\n      | AttributeError: 'Lock' object has no attribute '_owner_task'\n      +---------------- 2 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7f3a57111680>\n      +---------------- 3 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7f3a57111680>\n      +---------------- 4 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7f3a57111680>\n      +---------------- 5 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7f3a57111680>\n      +---------------- 6 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7f3a57111680>\n      +---------------- 7 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7f3a57111680>\n      +---------------- 8 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7f3a57111680>\n      +---------------- 9 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7f3a57111680>\n      +---------------- 10 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7f3a57111680>\n      +------------------------------------","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"clear_cache","time":{"start":1732763878512,"stop":1732763878512,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"global_fake_fs","time":{"start":1732763878512,"stop":1732763878517,"duration":5},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"global_fake_fs::0","time":{"start":1732763878647,"stop":1732763878648,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"trio(run=<function run at 0x7f3a59b500d0>)"},{"name":"parentSuite","value":"tests.unit.V1.client"},{"name":"suite","value":"test_client_async"},{"name":"host","value":"fv-az735-267"},{"name":"thread","value":"2066-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.unit.V1.client.test_client_async"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":138,"skipped":0,"passed":22,"unknown":0,"total":160},"items":[{"uid":"2f024b9e8d05ccd9","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/372//#testresult/2f024b9e8d05ccd9","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1732763733103,"stop":1732763733209,"duration":106}},{"uid":"2d133393e5b6bf49","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/368//#testresult/2d133393e5b6bf49","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1732677482081,"stop":1732677482185,"duration":104}},{"uid":"2cb29798ac1e9051","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/371//#testresult/2cb29798ac1e9051","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1732677337650,"stop":1732677337758,"duration":108}},{"uid":"1e9094f5b97e4c1e","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/367//#testresult/1e9094f5b97e4c1e","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1732590973773,"stop":1732590973877,"duration":104}},{"uid":"22ced6a5438fda4e","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/370//#testresult/22ced6a5438fda4e","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1732590827465,"stop":1732590827569,"duration":104}},{"uid":"ead4b0ec8ebd7140","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/366//#testresult/ead4b0ec8ebd7140","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1732504655827,"stop":1732504655931,"duration":104}},{"uid":"60871b5532e9e064","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/369//#testresult/60871b5532e9e064","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1732504506645,"stop":1732504506750,"duration":105}},{"uid":"79ee2f6f205c7836","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/365//#testresult/79ee2f6f205c7836","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1732418307128,"stop":1732418307233,"duration":105}},{"uid":"f1c044f7a3827c83","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/368//#testresult/f1c044f7a3827c83","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1732418154249,"stop":1732418154352,"duration":103}},{"uid":"246d55e74ccc55ea","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/364//#testresult/246d55e74ccc55ea","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1732331588115,"stop":1732331588218,"duration":103}},{"uid":"88a3f68472a01be7","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/367//#testresult/88a3f68472a01be7","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1732331444611,"stop":1732331444715,"duration":104}},{"uid":"f642341fa772152e","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/363//#testresult/f642341fa772152e","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1732245301018,"stop":1732245301124,"duration":106}},{"uid":"7f4c7d315c10f232","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/366//#testresult/7f4c7d315c10f232","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1732245173108,"stop":1732245173214,"duration":106}},{"uid":"85f730f69d74dadb","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/362//#testresult/85f730f69d74dadb","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1732158855378,"stop":1732158855485,"duration":107}},{"uid":"42f27f0f265379af","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/365//#testresult/42f27f0f265379af","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1732158710836,"stop":1732158710938,"duration":102}},{"uid":"bc4e2c429d45eb1e","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/361//#testresult/bc4e2c429d45eb1e","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1732072458250,"stop":1732072458356,"duration":106}},{"uid":"c3b8ee98998ac5b5","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/364//#testresult/c3b8ee98998ac5b5","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1732072313603,"stop":1732072313705,"duration":102}},{"uid":"717933d0efe6b1b","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/360//#testresult/717933d0efe6b1b","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731986090252,"stop":1731986090358,"duration":106}},{"uid":"42368cede8f8f119","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/363//#testresult/42368cede8f8f119","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731985958759,"stop":1731985958864,"duration":105}},{"uid":"adbc29e5d0ca1a02","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/359//#testresult/adbc29e5d0ca1a02","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731899857931,"stop":1731899858034,"duration":103}}]},"tags":["trio(run=<function run at 0x7f3a59b500d0>)"]},"source":"300cea5cb07123ab.json","parameterValues":[]}