{"uid":"e57c60b0852736d7","name":"test_true_concurent_requests","fullName":"tests.unit.client.test_client_async#test_true_concurent_requests","historyId":"76d4e56755e33d008f1c5ebb085831a5","time":{"start":1731640390678,"stop":1731640390836,"duration":158},"status":"broken","statusMessage":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","statusTrace":"+ Exception Group Traceback (most recent call last):\n  |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_core/_run.py\", line 1039, in __aexit__\n  |     raise combined_error_from_nursery\n  | exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Exception Group Traceback (most recent call last):\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pytest_trio/plugin.py\", line 195, in _fixture_manager\n    |     yield nursery_fixture\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pytest_trio/plugin.py\", line 250, in run\n    |     await self._func(**resolved_kwargs)\n    |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/tests/unit/conftest.py\", line 247, in wrapper\n    |     await func(*args, **kwargs)\n    |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/tests/unit/client/test_client_async.py\", line 186, in test_true_concurent_requests\n    |     for url in urls:\n    |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_core/_run.py\", line 1039, in __aexit__\n    |     raise combined_error_from_nursery\n    | exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (10 sub-exceptions)\n    +-+---------------- 1 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1663, in _send_handling_auth\n      |     raise exc\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1652, in _send_handling_auth\n      |     next_request = await auth_flow.asend(response)\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 174, in async_auth_flow\n      |     if self._lock.locked() and self._lock._owner_task == get_current_task():\n      | AttributeError: 'Lock' object has no attribute '_owner_task'\n      +---------------- 2 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7fa982b922c0>\n      +---------------- 3 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7fa982b922c0>\n      +---------------- 4 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7fa982b922c0>\n      +---------------- 5 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7fa982b922c0>\n      +---------------- 6 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7fa982b922c0>\n      +---------------- 7 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7fa982b922c0>\n      +---------------- 8 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7fa982b922c0>\n      +---------------- 9 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7fa982b922c0>\n      +---------------- 10 ----------------\n      | Traceback (most recent call last):\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1757, in get\n      |     return await self.request(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1530, in request\n      |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1617, in send\n      |     response = await self._send_handling_auth(\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/httpx/_client.py\", line 1642, in _send_handling_auth\n      |     request = await auth_flow.__anext__()\n      |   File \"/home/runner/work/firebolt-python-sdk/firebolt-python-sdk/src/firebolt/client/auth/base.py\", line 153, in async_auth_flow\n      |     await self._lock.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/anyio/_backends/_trio.py\", line 670, in acquire\n      |     await self.__original.acquire()\n      |   File \"/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/trio/_sync.py\", line 607, in acquire\n      |     raise trio.BrokenResourceError(\n      | trio.BrokenResourceError: Owner of this lock exited without releasing: <Task 'httpx._client.AsyncClient.get' at 0x7fa982b922c0>\n      +------------------------------------","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"clear_cache","time":{"start":1731640390672,"stop":1731640390672,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"global_fake_fs","time":{"start":1731640390672,"stop":1731640390677,"duration":5},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"global_fake_fs::0","time":{"start":1731640390858,"stop":1731640390859,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"trio(run=<function run at 0x7fa98604f160>)"},{"name":"parentSuite","value":"tests.unit.client"},{"name":"suite","value":"test_client_async"},{"name":"host","value":"fv-az1756-695"},{"name":"thread","value":"2155-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.unit.client.test_client_async"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":111,"skipped":0,"passed":22,"unknown":0,"total":133},"items":[{"uid":"81c136413067c1a5","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/355//#testresult/81c136413067c1a5","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731553800089,"stop":1731553800252,"duration":163}},{"uid":"8c33865cbd5c90fc","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/358//#testresult/8c33865cbd5c90fc","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731553666239,"stop":1731553666421,"duration":182}},{"uid":"eeb5793ae3ef1478","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/354//#testresult/eeb5793ae3ef1478","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731467365356,"stop":1731467365505,"duration":149}},{"uid":"63ff85a8dcd3d00f","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/357//#testresult/63ff85a8dcd3d00f","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731467220068,"stop":1731467220217,"duration":149}},{"uid":"4ffce644c505e3eb","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/353//#testresult/4ffce644c505e3eb","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731380866497,"stop":1731380866677,"duration":180}},{"uid":"e6862aa70d884ac0","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/356//#testresult/e6862aa70d884ac0","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731380725805,"stop":1731380725966,"duration":161}},{"uid":"b9fc53d2eed0dc1f","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/352//#testresult/b9fc53d2eed0dc1f","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731294619393,"stop":1731294619525,"duration":132}},{"uid":"aa5c8f5cee03f567","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/355//#testresult/aa5c8f5cee03f567","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731294468811,"stop":1731294468990,"duration":179}},{"uid":"6afb524d7c782d3","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/351//#testresult/6afb524d7c782d3","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731208216175,"stop":1731208216308,"duration":133}},{"uid":"d004e4b5ddeb942b","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/354//#testresult/d004e4b5ddeb942b","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731208087412,"stop":1731208087533,"duration":121}},{"uid":"e1f7d29597cd7075","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/350//#testresult/e1f7d29597cd7075","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731121962496,"stop":1731121962652,"duration":156}},{"uid":"c0d0ddb9044b1643","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/353//#testresult/c0d0ddb9044b1643","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731121573095,"stop":1731121573246,"duration":151}},{"uid":"6874a96b0e148636","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/349//#testresult/6874a96b0e148636","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731035329958,"stop":1731035330081,"duration":123}},{"uid":"ca618632038a5e4b","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/352//#testresult/ca618632038a5e4b","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1731035188377,"stop":1731035188530,"duration":153}},{"uid":"d22cb1ab8fa1b906","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/348//#testresult/d22cb1ab8fa1b906","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1730949012795,"stop":1730949012925,"duration":130}},{"uid":"d8378c8223124273","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/351//#testresult/d8378c8223124273","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1730948884459,"stop":1730948884663,"duration":204}},{"uid":"6174849c7b1975a1","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/347//#testresult/6174849c7b1975a1","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1730862504763,"stop":1730862504929,"duration":166}},{"uid":"6c2d84d9f49269d5","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/350//#testresult/6c2d84d9f49269d5","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1730862340412,"stop":1730862340546,"duration":134}},{"uid":"d1e9d8a2f9ef8cf8","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/346//#testresult/d1e9d8a2f9ef8cf8","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1730776138089,"stop":1730776138229,"duration":140}},{"uid":"87f87139733b3099","reportUrl":"https://firebolt-db.github.io/firebolt-python-sdk/_2bddcd39486ecb4e8d7d7debea7fd95bd3aab741_unit/349//#testresult/87f87139733b3099","status":"broken","statusDetails":"exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)","time":{"start":1730775970333,"stop":1730775970482,"duration":149}}]},"tags":["trio(run=<function run at 0x7fa98604f160>)"]},"source":"e57c60b0852736d7.json","parameterValues":[]}